"""fix member uniqueness constraints

Revision ID: 3c69472c6b81
Revises: 7de797828758
Create Date: 2026-06-22 13:37:44.706605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c69472c6b81'
down_revision: Union[str, Sequence[str], None] = '7de797828758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=False)
    op.drop_index(op.f('ix_members_phone'), table_name='members')
    op.create_index(op.f('ix_members_phone'), 'members', ['phone'], unique=False)
    op.create_unique_constraint('uq_member_email_user', 'members', ['email', 'user_id'])
    op.create_unique_constraint('uq_member_phone_user', 'members', ['phone', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_member_phone_user', 'members', type_='unique')
    op.drop_constraint('uq_member_email_user', 'members', type_='unique')
    op.drop_index(op.f('ix_members_phone'), table_name='members')
    op.create_index(op.f('ix_members_phone'), 'members', ['phone'], unique=True)
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    # ### end Alembic commands ###
